In [19]:
import cv2

img_source = "trump.jpg"

img = cv2.imread(img_source)

cv2.imshow('OMG',img)
cv2.waitKey()
cv2.destroyAllWindows()

In [22]:
!curl -L -o ./haarcascade_frontalface_default.xml https://raw.githubusercontent.com/opencv/opencv/master/data/haarcascades/haarcascade_frontalface_default.xml

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  1  908k    1 13710    0     0  11387      0  0:01:21  0:00:01  0:01:20 11387
 62  908k   62  565k    0     0   255k      0  0:00:03  0:00:02  0:00:01  255k
100  908k  100  908k    0     0   343k      0  0:00:02  0:00:02 --:--:--  343k


In [23]:
import cv2

faceCascade = cv2.CascadeClassifier("haarcascade_frontalface_default.xml")

img_source = "trump.jpg"

img = cv2.imread(img_source)

gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)

faces = faceCascade.detectMultiScale(
        gray,
        scaleFactor=1.1,
        minNeighbors=5,
        minSize=(30, 30),
)

for (x, y, w, h) in faces:
        cv2.rectangle(img, (x, y), (x+w, y+h), (0, 255, 0), 2)

cv2.imshow('OMG',img)
cv2.waitKey()
cv2.destroyAllWindows()

In [60]:
import cv2

faceCascade = cv2.CascadeClassifier("haarcascade_frontalface_default.xml")

video_capture = cv2.VideoCapture(0)


while True:
    # Capture frame-by-frame
    ret, frame = video_capture.read()
    gray = cv2.cvtColor(frame, cv2.COLOR_BGR2GRAY)

    faces = faceCascade.detectMultiScale(
        gray,
        scaleFactor=1.1,
        minNeighbors=5,
        minSize=(30, 30),
    )

    # Draw a rectangle around the faces
    for (x, y, w, h) in faces:
        cv2.rectangle(frame, (x, y), (x+w, y+h), (0, 255, 0), 2)

    # Display the resulting frame
    cv2.imshow('Video', frame)

    if cv2.waitKey(1) & 0xFF == ord('q'):
        break

# When everything is done, release the capture
video_capture.release()
cv2.destroyAllWindows()



In [106]:
import cv2

src = cv2.imread("trump.jpg", cv2.IMREAD_COLOR)
a=200
dst = src.copy() 
dst = src[0:a, 0:a]

cv2.imshow("src", src)
cv2.imshow("dst", dst)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [15]:
import cv2

src = cv2.imread("trump.jpg", cv2.IMREAD_COLOR)

dst = src.copy() 
roi = src[100:600, 200:700]
dst[100:600, 100:600] = roi

cv2.imshow("src", src)
cv2.imshow("dst", dst)
cv2.waitKey(0)
cv2.destroyAllWindows()


In [32]:
import numpy as np

a = [1, 2, 3, 4, 5]
b = np.array(a)
c = np.array([1, 3, 5])
d = a

print(a)
print(b)
print(c)
print(d)

[1, 2, 3, 4, 5]
[1 2 3 4 5]
[1 3 5]
[1, 2, 3, 4, 5]


In [31]:
import numpy as np

a = [1, 2, 3, 4, 5]
b = np.array(a)
c = np.array([1, 3, 5])

print(b[2])
print(a[-2])
print(c[1:3])

3
4
[3 5]


In [34]:
L = ["일","이","삼"]
T = (1, 2, 3)
S = "윤대희"
total = 0

for i in L:
    print(i)

for i in T:
    print(i)

for i in S:
    print(i)

for i in range(1,10):
    total = total + i
print (total)

일
이
삼
1
2
3
윤
대
희
45


In [52]:
import numpy as np
a=[]
for i in range(10):
    a.append(i)
print(a)


[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]


In [119]:
import cv2
import numpy as np

src = cv2.imread("trump.jpg", cv2.IMREAD_COLOR)
#img1= cv2.resize(src,(200,200))

a=0
b=0
c=[]
n=1
dst = src.copy() 
for i in range(3):
    #print(a,":::")

    for j in range(5):
        #print(b)
        c.append(dst[b:b+100,a:a+100]) #0:100, 0:100 -> 100:200, 0:100 -> 200:300, 0:100
                                       #0:100, 100:200 -> 100:200, 100:200 -> 200:300, 
        b=b+100
        n=n+1
    
    a=a+100
    b=0
    #print(":")

print(c[0].shape)
print(c[1].shape)
print(c[2].shape)
print(c[3].shape)
print(c[4].shape)
print(len(c))
img2=cv2.hconcat([c[0],c[1],c[2],c[3])

cv2.imshow('showimg',img2)
cv2.waitKey(0)
cv2.destroyAllWindows()

(100, 100, 3)
(100, 100, 3)
(100, 100, 3)
(100, 100, 3)
(5, 100, 3)
15


In [16]:
import cv2
import argparse

"""
ap=argparse.ArgumentParser()
ap.add_argument("-i", "--image", required=True, help="path to the image")
args=vars(ap.parse_args())
"""

#이미지 경로
image=cv2.imread("trump.jpg") #배열로 구성, (세로, 가로, 채널)

#이미지 정보 출력
print("width:{}pixels",format(image.shape[1])) #이미지의 가로
print("height:{}piexels",format(image.shape[0])) #이미지의 세로
print("channels:{}",format(image.shape[2]))


#이미지 저장
cv2.imwrite("newimage.jpg",image)

#이미지 자르기
cut=image[0:100, 0:100] #높이, 너비
#이미지 보여주기
cv2.imshow("corona", cut)
cv2.waitKey(0)

width:{}pixels 720
height:{}piexels 405
channels:{} 3


-1

In [1]:
import cv2
import argparse

image=cv2.imread("trump.jpg")
#cv2.imshow("preimage", image)

b=100;

#image의 RGB값 받기(opencv는 BGR순서)
a=image[0,0]
print(a)
#print("Pixel at (0,0) -red:{},Green:{}, Blue: {}", format(r,g,b))
print(format(a))

corner=image[0:100, 0:100]
cv2.imshow("Corner", corner)

image[0:b, 0:b]=(0,255,0)

cv2.imshow("Udated", image)
cv2.waitKey(0)

[24  3  5]
[24  3  5]


-1

In [2]:
import cv2
import numpy as np

canvas=np.zeros((300,300,3), dtype="uint8")

image=cv2.imread("trump.jpg")

green=(0,255,0)
cv2.line(canvas,(0,0),(300,300),green)
cv2.imshow("canvas",canvas)
cv2.waitKey(0)

cv2.rectangle(image, (50,200),(300,300),green,5)
cv2.imshow("canvas",image)
cv2.waitKey(0)


-1

In [7]:
import numpy as np
import cv2

canvas=np.zeros((300,300,3), dtype="uint8")
(centerX, centerY)=(canvas.shape[1]//2, canvas.shape[0]//2)
white=(255,255,255)

for r in range(0,175,25):#0~174까지 +25해가며 배열만듦.
    cv2.circle(canvas,(centerX, centerY), r, white)
    
cv2.imshow("Canvas", canvas)
cv2.waitKey(0)

for i in range(0,25):
    radius=np.random.randint(5,high=200)
    color=np.random.randint(0,high=256, size=(3,)).tolist()
    pt=np.random.randint(0,high=300, size=(2,))
    cv2.circle(canvas, tuple(pt), radius, color, -1)
    
    cv2.imshow("Canvas", canvas)
    cv2.waitKey(0)



In [81]:
import cv2
import numpy as np

#이미지 경로
image=cv2.imread("trump.jpg") #배열로 구성, (세로, 가로, 채널)

#이미지 정보 출력
wsize=image.shape[1]
hsize=image.shape[0]
print("가로=",wsize," ","세로=",hsize," ", "채널=",image.shape[2])

#5등분 했을때 크기
divwsize=wsize//5
divhsize=hsize//5

print("5등분 하면 가로/세로=",divwsize, divhsize)

green=(0,255,0)
aimg=[]
for i in range(0,hsize,divhsize):
    for j in range(0,wsize,divwsize):  
        aimg.append(image[i:i+divhsize, j:j+divwsize])
        
    
    
print(np.shape(aimg))

#---------------------------
image0=cv2.hconcat([aimg[0],aimg[1],aimg[2],aimg[3],aimg[4]])
image1=cv2.hconcat([aimg[5],aimg[6],aimg[7],aimg[8],aimg[9]])
image2=cv2.hconcat([aimg[10],aimg[11],aimg[12],aimg[13],aimg[14]])
image3=cv2.hconcat([aimg[15],aimg[16],aimg[17],aimg[18],aimg[19]])
image4=cv2.hconcat([aimg[20],aimg[21],aimg[22],aimg[23],aimg[24]])

imageall=cv2.vconcat([image0,image1,image2,image3,image4])


cv2.imshow("zzazan",imageall)
cv2.waitKey(0)
       

가로= 720   세로= 405   채널= 3
5등분 하면 가로/세로= 144 81
(25, 81, 144, 3)


-1

In [66]:
import numpy as np

j=0;
k=0;
a=[];
for i in range(0,2):
    for j in range(0,2):
        a.append(j)
    
print(a)

b=[];
b=np.arange(16)
print(b)
print(b.reshape(-1,4))





[0, 1, 0, 1]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


In [29]:
j=0;
k=0;
a=[];
for i in range(0,10,1):
    print(i)
  

0
1
2
3
4
5
6
7
8
9


In [25]:
print("내 이름은 %s이고, 나이는 %d 입니다." %("홍딜동", 20))
print("숫자 채우기:{}".format(999))

내 이름은 홍딜동이고, 나이는 20 입니다.
숫자 채우기:999
